import { test, expect } from '@playwright/test';
test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/inicio');
  await page.getByRole('button', { name: 'Volver a cargar' }).click();
  await expect(page.getByRole('heading', { name: 'FUNCIONAL' }).first()).toBeVisible();
  await page.getByRole('button', { name: 'REGISTRARSE' }).click();
  await page.getByRole('textbox', { name: 'Usuario' }).click();
  await page.getByRole('textbox', { name: 'Usuario' }).click();
  await page.getByRole('textbox', { name: 'Contraseña', exact: true }).click();
  await page.getByRole('textbox', { name: 'Contraseña', exact: true }).click();
  await page.getByRole('textbox', { name: 'Confirmar Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).click();
  await page.getByRole('textbox', { name: 'Apellido' }).click();
  await page.getByRole('textbox', { name: 'Apellido' }).dblclick();
  await page.getByRole('textbox', { name: 'Email' }).dblclick();
  await page.getByRole('button', { name: 'Registrarse', exact: true }).click();
  await page.getByRole('textbox', { name: 'Usuario' }).click();
  await page.getByRole('textbox', { name: 'Usuario' }).fill('bianca12');
  await page.getByRole('textbox', { name: 'Contraseña', exact: true }).click();
  await page.getByRole('textbox', { name: 'Contraseña', exact: true }).fill('12345678');
  await page.getByRole('textbox', { name: 'Confirmar Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Confirmar Contraseña' }).fill('12345678');
  await page.getByRole('textbox', { name: 'Nombre' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).fill('bian');
  await page.getByRole('textbox', { name: 'Apellido' }).click();
  await page.getByRole('textbox', { name: 'Apellido' }).fill('lopez');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('biaanlopez@gmail.com');
  page.once('dialog', dialog => {
console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Registrarse', exact: true }).click();
});